// ─── Book Code Generator ──────────────────────────
function generateBookCode(year, genre, innerGenre, copyNum) {
  const y = String(year).slice(-2);
  const g = genre.slice(0, 3).toUpperCase();
  const ig = innerGenre.slice(0, 2).toUpperCase();
  const c = String(copyNum).padStart(3, '0');
  return `${y}${g}${ig}${c}`;
}

// ─── Students Database ────────────────────────────
export const STUDENTS = [
  {
    id: 's1',
    libraryCardNumber: 'BMSCE2024001',
    name: 'Arjun Sharma',
    email: 'arjun.sharma@bmsce.ac.in',
    usn: '1BM22CS001',
    password: 'student123',
    isBlacklisted: false,
    borrowedBooks: ['b1', 'b3'],
    fines: 25,
  },
  {
    id: 's2',
    libraryCardNumber: 'BMSCE2024002',
    name: 'Priya Nair',
    email: 'priya.nair@bmsce.ac.in',
    usn: '1BM22CS002',
    password: 'student123',
    isBlacklisted: false,
    borrowedBooks: ['b5'],
    fines: 0,
  },
  {
    id: 's3',
    libraryCardNumber: 'BMSCE2024003',
    name: 'Rahul Gupta',
    email: 'rahul.gupta@bmsce.ac.in',
    usn: '1BM22EC003',
    password: 'student123',
    isBlacklisted: true,
    borrowedBooks: ['b7', 'b10', 'b12'],
    fines: 340,
  },
  {
    id: 's4',
    libraryCardNumber: 'BMSCE2024004',
    name: 'Sneha Reddy',
    email: 'sneha.reddy@bmsce.ac.in',
    usn: '1BM22IS004',
    password: 'student123',
    isBlacklisted: false,
    borrowedBooks: [],
    fines: 0,
  },
];

// ─── Admin Account ─────────────────────────────────
export const ADMIN = {
  id: 'admin1',
  email: 'admin@bmsce.ac.in',
  password: 'admin123',
  name: 'Library Admin',
};

// ─── Books Collection ──────────────────────────────
export const BOOKS = [
  {
    id: 'b1',
    title: 'Introduction to Algorithms',
    author: 'Thomas H. Cormen',
    genre: 'Computer Science',
    innerGenre: 'Algorithms',
    year: 2009,
    totalCopies: 5,
    availableCopies: 2,
    cost: 650,
    coverUrl: 'https://picsum.photos/seed/algo/200/300',
    description: 'A comprehensive textbook covering a broad range of algorithms in depth, yet makes their design and analysis accessible to all levels of readers.',
    isbn: '978-0262033848',
    bookCode: '',
    reservedBy: null,
  },
  {
    id: 'b2',
    title: 'Clean Code',
    author: 'Robert C. Martin',
    genre: 'Software Engineering',
    innerGenre: 'Best Practices',
    year: 2008,
    totalCopies: 3,
    availableCopies: 3,
    cost: 450,
    coverUrl: 'https://picsum.photos/seed/clean/200/300',
    description: 'A handbook of agile software craftsmanship that provides best practices for writing clean, maintainable code.',
    isbn: '978-0132350884',
    bookCode: '',
    reservedBy: null,
  },
  {
    id: 'b3',
    title: 'Design Patterns',
    author: 'Erich Gamma',
    genre: 'Software Engineering',
    innerGenre: 'Design',
    year: 1994,
    totalCopies: 4,
    availableCopies: 1,
    cost: 550,
    coverUrl: 'https://picsum.photos/seed/design/200/300',
    description: 'Classic reference for design patterns in object-oriented software, introducing 23 essential patterns.',
    isbn: '978-0201633610',
    bookCode: '',
    reservedBy: null,
  },
  {
    id: 'b4',
    title: 'Artificial Intelligence: A Modern Approach',
    author: 'Stuart Russell',
    genre: 'Computer Science',
    innerGenre: 'AI',
    year: 2020,
    totalCopies: 6,
    availableCopies: 4,
    cost: 800,
    coverUrl: 'https://picsum.photos/seed/aibook/200/300',
    description: 'The most comprehensive, up-to-date introduction to the theory and practice of artificial intelligence.',
    isbn: '978-0134610993',
    bookCode: '',
    reservedBy: null,
  },
  {
    id: 'b5',
    title: 'Database System Concepts',
    author: 'Abraham Silberschatz',
    genre: 'Computer Science',
    innerGenre: 'Database',
    year: 2019,
    totalCopies: 4,
    availableCopies: 2,
    cost: 700,
    coverUrl: 'https://picsum.photos/seed/dbbook/200/300',
    description: 'Comprehensive coverage of database systems including relational model, SQL, and transaction management.',
    isbn: '978-0078022159',
    bookCode: '',
    reservedBy: null,
  },
  {
    id: 'b6',
    title: 'Computer Networks',
    author: 'Andrew S. Tanenbaum',
    genre: 'Computer Science',
    innerGenre: 'Networks',
    year: 2021,
    totalCopies: 5,
    availableCopies: 5,
    cost: 600,
    coverUrl: 'https://picsum.photos/seed/network/200/300',
    description: 'Classic textbook on computer networking covering protocols, architectures, and applications.',
    isbn: '978-0132126953',
    bookCode: '',
    reservedBy: null,
  },
  {
    id: 'b7',
    title: 'Operating System Concepts',
    author: 'Abraham Silberschatz',
    genre: 'Computer Science',
    innerGenre: 'OS',
    year: 2018,
    totalCopies: 3,
    availableCopies: 0,
    cost: 550,
    coverUrl: 'https://picsum.photos/seed/osbook/200/300',
    description: 'Essential concepts and implementation strategies for modern operating systems.',
    isbn: '978-1119800361',
    bookCode: '',
    reservedBy: 's2',
  },
  {
    id: 'b8',
    title: 'The Pragmatic Programmer',
    author: 'David Thomas',
    genre: 'Software Engineering',
    innerGenre: 'Career',
    year: 2019,
    totalCopies: 2,
    availableCopies: 2,
    cost: 400,
    coverUrl: 'https://picsum.photos/seed/pragmatic/200/300',
    description: 'Timeless coding advice covering everything from personal responsibility to architecture design.',
    isbn: '978-0135957059',
    bookCode: '',
    reservedBy: null,
  },
  {
    id: 'b9',
    title: 'Discrete Mathematics and Its Applications',
    author: 'Kenneth H. Rosen',
    genre: 'Mathematics',
    innerGenre: 'Discrete',
    year: 2018,
    totalCopies: 6,
    availableCopies: 3,
    cost: 500,
    coverUrl: 'https://picsum.photos/seed/discrete/200/300',
    description: 'Standard reference for discrete math concepts used in computer science.',
    isbn: '978-0073383095',
    bookCode: '',
    reservedBy: null,
  },
  {
    id: 'b10',
    title: 'Engineering Mathematics',
    author: 'B.S. Grewal',
    genre: 'Mathematics',
    innerGenre: 'Engineering',
    year: 2017,
    totalCopies: 8,
    availableCopies: 5,
    cost: 350,
    coverUrl: 'https://picsum.photos/seed/engmath/200/300',
    description: 'Comprehensive engineering mathematics covering calculus, linear algebra, and differential equations.',
    isbn: '978-8174091956',
    bookCode: '',
    reservedBy: null,
  },
  {
    id: 'b11',
    title: 'Digital Logic Design',
    author: 'Morris Mano',
    genre: 'Electronics',
    innerGenre: 'Digital',
    year: 2017,
    totalCopies: 4,
    availableCopies: 4,
    cost: 400,
    coverUrl: 'https://picsum.photos/seed/digital/200/300',
    description: 'Foundational textbook on digital logic circuits and design methodology.',
    isbn: '978-0134468907',
    bookCode: '',
    reservedBy: null,
  },
  {
    id: 'b12',
    title: 'Signals and Systems',
    author: 'Alan V. Oppenheim',
    genre: 'Electronics',
    innerGenre: 'Signals',
    year: 2015,
    totalCopies: 3,
    availableCopies: 0,
    cost: 500,
    coverUrl: 'https://picsum.photos/seed/signals/200/300',
    description: 'Comprehensive treatment of signals and systems theory for engineering students.',
    isbn: '978-0138147570',
    bookCode: '',
    reservedBy: null,
  },
  {
    id: 'b13',
    title: 'Machine Learning',
    author: 'Tom M. Mitchell',
    genre: 'Computer Science',
    innerGenre: 'ML',
    year: 2017,
    totalCopies: 4,
    availableCopies: 3,
    cost: 600,
    coverUrl: 'https://picsum.photos/seed/mlbook/200/300',
    description: 'Broad introduction to machine learning covering statistical and computational approaches.',
    isbn: '978-0070428072',
    bookCode: '',
    reservedBy: null,
  },
  {
    id: 'b14',
    title: 'Data Structures Using C',
    author: 'Reema Thareja',
    genre: 'Computer Science',
    innerGenre: 'Data Structures',
    year: 2018,
    totalCopies: 5,
    availableCopies: 2,
    cost: 350,
    coverUrl: 'https://picsum.photos/seed/dsbook/200/300',
    description: 'Covers fundamental data structures and algorithms using C programming language.',
    isbn: '978-0198099307',
    bookCode: '',
    reservedBy: null,
  },
  {
    id: 'b15',
    title: 'Compiler Design',
    author: 'Alfred V. Aho',
    genre: 'Computer Science',
    innerGenre: 'Compilers',
    year: 2006,
    totalCopies: 3,
    availableCopies: 3,
    cost: 500,
    coverUrl: 'https://picsum.photos/seed/compiler/200/300',
    description: 'The dragon book — classic reference for compiler construction techniques and theory.',
    isbn: '978-0321486813',
    bookCode: '',
    reservedBy: null,
  },
  {
    id: 'b16',
    title: 'Microprocessors and Microcontrollers',
    author: 'Ramesh Gaonkar',
    genre: 'Electronics',
    innerGenre: 'Micro',
    year: 2013,
    totalCopies: 4,
    availableCopies: 1,
    cost: 450,
    coverUrl: 'https://picsum.photos/seed/micro/200/300',
    description: 'Detailed coverage of microprocessor architecture and programming with real-world applications.',
    isbn: '978-8131732465',
    bookCode: '',
    reservedBy: null,
  },
];

// Generate book codes
BOOKS.forEach((book, idx) => {
  book.bookCode = generateBookCode(book.year, book.genre, book.innerGenre, idx + 1);
});

// ─── Borrow Records ───────────────────────────────
const today = new Date();
const daysAgo = (n) => {
  const d = new Date(today);
  d.setDate(d.getDate() - n);
  return d.toISOString().split('T')[0];
};
const daysFromNow = (n) => {
  const d = new Date(today);
  d.setDate(d.getDate() + n);
  return d.toISOString().split('T')[0];
};

export const BORROW_RECORDS = [
  {
    id: 'br1',
    studentId: 's1',
    bookId: 'b1',
    borrowDate: daysAgo(5),
    dueDate: daysFromNow(2),
    returnDate: null,
    fine: 0,
    status: 'active',
  },
  {
    id: 'br2',
    studentId: 's1',
    bookId: 'b3',
    borrowDate: daysAgo(3),
    dueDate: daysFromNow(4),
    returnDate: null,
    fine: 0,
    status: 'active',
  },
  {
    id: 'br3',
    studentId: 's2',
    bookId: 'b5',
    borrowDate: daysAgo(6),
    dueDate: daysFromNow(1),
    returnDate: null,
    fine: 0,
    status: 'active',
  },
  {
    id: 'br4',
    studentId: 's3',
    bookId: 'b7',
    borrowDate: daysAgo(15),
    dueDate: daysAgo(8),
    returnDate: null,
    fine: 340,
    status: 'overdue',
  },
  {
    id: 'br5',
    studentId: 's3',
    bookId: 'b10',
    borrowDate: daysAgo(4),
    dueDate: daysFromNow(3),
    returnDate: null,
    fine: 0,
    status: 'active',
  },
  {
    id: 'br6',
    studentId: 's3',
    bookId: 'b12',
    borrowDate: daysAgo(10),
    dueDate: daysAgo(3),
    returnDate: null,
    fine: 15,
    status: 'overdue',
  },
  // Past records
  {
    id: 'br7',
    studentId: 's1',
    bookId: 'b2',
    borrowDate: daysAgo(30),
    dueDate: daysAgo(23),
    returnDate: daysAgo(24),
    fine: 0,
    status: 'returned',
  },
  {
    id: 'br8',
    studentId: 's1',
    bookId: 'b4',
    borrowDate: daysAgo(60),
    dueDate: daysAgo(53),
    returnDate: daysAgo(50),
    fine: 15,
    status: 'returned',
  },
  {
    id: 'br9',
    studentId: 's2',
    bookId: 'b9',
    borrowDate: daysAgo(20),
    dueDate: daysAgo(13),
    returnDate: daysAgo(13),
    fine: 0,
    status: 'returned',
  },
  {
    id: 'br10',
    studentId: 's4',
    bookId: 'b11',
    borrowDate: daysAgo(14),
    dueDate: daysAgo(7),
    returnDate: daysAgo(6),
    fine: 0,
    status: 'returned',
  },
];

// ─── Issue Requests ────────────────────────────────
export const ISSUE_REQUESTS = [
  {
    id: 'ir1',
    studentId: 's4',
    bookId: 'b4',
    requestDate: daysAgo(1),
    status: 'pending',
  },
  {
    id: 'ir2',
    studentId: 's2',
    bookId: 'b13',
    requestDate: daysAgo(0),
    status: 'pending',
  },
];

// ─── Advance Reservations ──────────────────────────
export const ADVANCE_RESERVATIONS = [
  {
    id: 'ar1',
    studentId: 's2',
    bookId: 'b7',
    reservationDate: daysAgo(2),
    status: 'waiting',
    expiresAt: null,
  },
  {
    id: 'ar2',
    studentId: 's1',
    bookId: 'b12',
    reservationDate: daysAgo(1),
    status: 'waiting',
    expiresAt: null,
  },
];

// ─── Notifications ─────────────────────────────────
export const NOTIFICATIONS = [
  {
    id: 'n1',
    studentId: 's1',
    type: 'return_reminder',
    title: 'Return Reminder',
    message: '"Introduction to Algorithms" is due in 2 days. Please return it on time to avoid fines.',
    timestamp: daysAgo(0) + 'T09:00:00',
    read: false,
    icon: 'clock',
  },
  {
    id: 'n2',
    studentId: 's1',
    type: 'issue_approved',
    title: 'Issue Approved',
    message: 'Your request for "Clean Code" has been approved. Please collect it from the library.',
    timestamp: daysAgo(1) + 'T14:30:00',
    read: false,
    icon: 'check-circle',
  },
  {
    id: 'n3',
    studentId: 's1',
    type: 'fine_update',
    title: 'Fine Cleared',
    message: 'Your fine of ₹15 for "AI: A Modern Approach" has been recorded. Please clear it at the library.',
    timestamp: daysAgo(3) + 'T10:00:00',
    read: true,
    icon: 'alert-circle',
  },
  {
    id: 'n4',
    studentId: 's2',
    type: 'reservation_available',
    title: 'Book Available!',
    message: '"Operating System Concepts" is now available. Your reservation is valid for 24 hours.',
    timestamp: daysAgo(0) + 'T11:00:00',
    read: false,
    icon: 'book-open',
  },
  {
    id: 'n5',
    studentId: 's3',
    type: 'fine_update',
    title: 'Fine Warning',
    message: 'Your account is BLACKLISTED due to overdue books. Return immediately to restore access.',
    timestamp: daysAgo(0) + 'T08:00:00',
    read: false,
    icon: 'alert-triangle',
  },
  {
    id: 'n6',
    studentId: 's2',
    type: 'return_reminder',
    title: 'Return Reminder',
    message: '"Database System Concepts" is due tomorrow. Please return it on time.',
    timestamp: daysAgo(0) + 'T09:00:00',
    read: false,
    icon: 'clock',
  },
];

// ─── Genre List ────────────────────────────────────
export const GENRES = [
  'Computer Science',
  'Software Engineering',
  'Mathematics',
  'Electronics',
  'Mechanical',
  'Civil',
  'Physics',
  'Chemistry',
];
